apiVersion: v1
kind: Service
metadata:
  name: nginx-jenkins-pipeline
  labels:
    service: nginx-jenkins
spec:
  type: NodePort
  selector:
    component: nginx-jenkins
  ports:
    - nodePort: 8085
      port: 8030
      targetPort: 80